---
title: Federal Spending on Education and Its Relation to Global and Provincial Standardized Testing Scores
author: 
  - David James Dimalanta
thanks: "Code and data are available at: https://github.com/davidjamesdimalanta/Federal_Education_Policy"
date: today
date-format: long
abstract: "This paper provides a comprehensive analysis of government spending on education policies and their correlation with academic performance, as indicated by scores from the Programme for International Student Assessment (PISA) and the Ontario Secondary School Literacy Test (OSSLT). By examining various countries' financial investments in their education systems, such as Chile, Finland, and Canada, this paper aims to identify patterns and outcomes that highlight the effectiveness of these expenditures. Through a comparative approach, it assesses how different levels and methods of funding impact student achievement in international benchmarks like PISA, which evaluates reading, mathematics, and science literacy among 15-year-olds, and in specific contexts such as Ontario's literacy requirement, the OSSLT."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false
library(ggplot2)
library(tidyverse)
```
# Introduction

This paper provides a comprehensive analysis of government spending on education policies and their correlation with academic performance, as indicated by scores from the Programme for International Student Assessment (PISA) and the Ontario Secondary School Literacy Test (OSSLT). By examining various countries' financial investments in their education systems, such as Chile, Finland, and Canada, this paper aims to identify patterns and outcomes that highlight the effectiveness of these expenditures. Through a comparative approach, it assesses how different levels and methods of funding impact student achievement in international benchmarks like PISA, which evaluates reading, mathematics, and science literacy among 15-year-olds, and in specific contexts such as Ontario's literacy requirement, the OSSLT.

\newpage


# References


